steps:
# Build the WordPress Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/wordpress-repo/wordpress:$COMMIT_SHA', '.']

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/wordpress-repo/wordpress:$COMMIT_SHA']

# Apply Kubernetes manifests
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'kubernetes/'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Update the image in the WordPress deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/wordpress'
  - 'wordpress=us-central1-docker.pkg.dev/$PROJECT_ID/wordpress-repo/wordpress:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/wordpress-repo/wordpress:$COMMIT_SHA'

options:
  logging: GCS_ONLY
logsBucket: 'gs://wordpress-bucket-wordpress-project-sigma'