steps:
name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform version
    terraform init
    terraform validate

name: 'gcr.io/cloud-builders/docker'
  args: ['version']

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY