steps:
# Build the WordPress Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA', '.']

# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/wordpress'
  - 'wordpress=gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

images:
- 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
