steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA', '.']

# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA']

# Update the kubernetes deployment to use the new image
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/wordpress'
  - 'wordpress=gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Apply all resources from the single YAML file
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/wordpress_cloudsql.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

# Deploy using gke-deploy
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=wordpress_cloudsql.yaml
  - --location=us-central1-a
  - --cluster=wordpress-cluster

images:
- 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA'

options:
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

serviceAccount: 'projects/wordpress-project-sigma/serviceAccounts/cloudsql-proxy@wordpress-project-sigma.iam.gserviceaccount.com'

options:
  logging: GCS_ONLY
logsBucket: 'gs://wordpress-bucket-wordpress-project-sigma'
