steps:
  # Build the WordPress Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: ['build', '-t', 'gcr.io/wordpress-project-sigma/wordpress:$COMMIT_SHA', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args: ['push', 'gcr.io/wordpress-project-sigma/wordpress:$COMMIT_SHA']

  # Deploy the deployment YAML
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'apply'
    args:
      - 'apply'
      - '-f'
      - 'wordpress-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_COMPUTE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy'
    args:
      - 'set'
      - 'image'
      - 'deployment/wordpress'
      - 'wordpress=gcr.io/wordpress-project-sigma/wordpress:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

  # Test the deployment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'test'
    args: ['-f', 'http://${_WORDPRESS_IP}']
    waitFor: ['deploy']

images:
  - 'gcr.io/wordpress-project-sigma/wordpress:$COMMIT_SHA'

substitutions:
  _COMPUTE_REGION: us-central1
  _CLUSTER_NAME: wordpress-cluster
  _WORDPRESS_IP: # Add your WordPress service IP here after deployment

options:
  substitution_option: 'ALLOW_LOOSE'

options:
  logging: GCS_ONLY
logsBucket: 'gs://wordpress-project-sigma-media/logs'