steps:
# Build the WordPress Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wordpress:$COMMIT_SHA', '.']

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wordpress:$COMMIT_SHA']

# Run Terraform init, plan, and apply with error handling
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd terraform
    terraform init
    terraform plan -out=tfplan
    if terraform apply -auto-approve tfplan; then
      echo "Terraform apply succeeded"
      echo "TERRAFORM_SUCCESS=true" >> $BUILDER_OUTPUT/terraform_status
    else
      echo "Terraform apply failed"
      echo "TERRAFORM_SUCCESS=false" >> $BUILDER_OUTPUT/terraform_status
      exit 1
    fi
  env:
  - 'TF_VAR_project_id=${PROJECT_ID}'
  - 'TF_VAR_region=${_REGION}'

# Get GKE credentials and deploy if Terraform was successful
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    if [ "$(cat $BUILDER_OUTPUT/terraform_status | grep TERRAFORM_SUCCESS=true)" ]; then
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_REGION} --project ${PROJECT_ID}
      
      echo "$$DB_PASSWORD" | kubectl create secret generic wordpress-db-secret --from-file=password=/dev/stdin --dry-run=client -o yaml | kubectl apply -f -
      
      kubectl apply -f kubernetes/
      if [ $? -ne 0 ]; then
        echo "Kubernetes deployment failed."
        exit 1
      fi
    else
      echo "Skipping Kubernetes deployment due to Terraform failure"
      exit 1
    fi
  secretEnv: ['DB_PASSWORD']

substitutions:
  _REGION: us-central1
  _REPO_NAME: wordpress-repo
  _CLUSTER_NAME: wordpress-cluster

availableSecrets:
  secretManager:
  - versionName: projects/wordpress-project-sigma/secrets/wordpress-db-password/versions/latest
    env: 'DB_PASSWORD'

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/wordpress:$COMMIT_SHA'

options:
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

logsBucket: 'gs://wordpress-project-sigma-logs'