apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany  # Changed from ReadWriteOnce to support multiple nodes
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo  # Adjust this based on your GKE storage class