apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secrets
type: Opaque
stringData:
  username: wordpress
  password: ${DB_PASSWORD} # This will be replaced by the actual password from Secret Manager

